export const en = {
  album: 'Album',
  albums: 'Albums',
  artist: 'Artist',
  artists: 'Artists',
  cancel: 'Cancel',
  done: 'Done',
  edit: 'Edit',
  favoriteAdd: 'Add to favorites',
  favoriteArtists: 'Favorite Artists',
  favoriteRemove: 'Remove from favorites',
  favoriteSongs: 'Favorite Songs',
  library: 'Library',
  openAppSettings: 'open app settings',
  permissionDenied: 'Permissions are denied. You can change permissions in app settings.',
  playlist: 'Playlist',
  playlistAdd: 'Add to a playlist',
  playlistCreate: 'New playlist',
  playlistEnter: 'Enter the playlist name',
  playlistName: 'Playlist name',
  playlistRemove: 'Remove playlist',
  playlistRemoveConfirm: 'Remove the playlist?',
  playlistExistConfirm: 'Already registered. Add anyway?',
  playlists: 'Playlists',
  recentlyAdded: 'Recently Added',
  shortcut: 'Shortcut',
  shortcutAdd: 'Add to a shortcut',
  shortcutRemove: 'Remove from shortcut',
  songs: 'Songs',
};
